### ISSUE TITLE
I am constantly getting press any key to continue in console logs (v.1.43)

### ISSUE THREAD

**Issue by NudeNULL** [Lolliedieb/lolMiner-releases#1012]
![image](https://user-images.githubusercontent.com/15786742/152606181-66221dcb-9c5c-4ebc-a08f-245bda901a14.png)

**Comment by NudeNULL** [comment]
Even if I try to mine only TONCOIN.

In version 1.42 everything is fine.

**Comment by Vinasis01** [comment]
I am having the same issue on my LHR rig that consist of 3080 LHR cards and 3070 TI cards.
was about to make a post but saw this thread so commented here.

**Comment by nCr78** [comment]
Same here.. any temporary fix for this at least? I see it happened to everyone at once. I'm on flexpool and tonwhales. Maybe it has something to do with this. Restart doesn't work.

**Comment by Vinasis01** [comment]
I am on Nicehash for ETH and tonwhales for TON, maybe it's from the miner side, hope it gets fixed soon.

**Comment by nCr78** [comment]
Now it's working again. @Lolliedieb please tell us this isn't due to your fee server being down or something. You implemented a stopping mechanism that stopped everyone's rigs.. Sorry for making assumptions, it's just kinda funny 😄

**Comment by Vinasis01** [comment]
Hmm this is worrisome, I was planning to put all my rigs on it and sleep but now I'll sleep it over and tomorrow try the rigs one by one...having many rigs that might shutdown while asleep is a loss.

**Comment by jgonzis** [comment]
For LHR try using Nvidia Drivers 472.12 please...

**Comment by Lolliedieb** [comment]
No idea why it crashes there... have only had it once on a card of mine where I gave too much oc on a card... new modes very stressing for cards ^^

**Comment by wowlpv500** [comment]
also getting this error
occcured on amd only rigs, and nvidia only rigs

**Comment by jgonzis** [comment]
> also getting this error occcured on amd only rigs, and nvidia only rigs

OS?
GPUs?
Drivers?
Virtual Memory?

Without information is impossible to help

**Comment by wowlpv500** [comment]
> > also getting this error occcured on amd only rigs, and nvidia only rigs
> 
> OS? GPUs? Drivers? Virtual Memory?
> 
> Without information is impossible to help

OS - Windows 7 for NVIDIA rig
2x 3080 and 2x 3060 all LHR
3080 set to lock core 1250, and 3060 lock core 1450
Memory overclocks set at +1250
driver 472.12
overclocks set using nvidia smi

OS - windows 10 for amd rig
5x 6600 non XT
core set 1750
memory at 1900
overclocks set using msi afterburner
18/10/2021 driver

**Comment by jgonzis** [comment]
> > > also getting this error occcured on amd only rigs, and nvidia only rigs
> > 
> > 
> > OS? GPUs? Drivers? Virtual Memory?
> > Without information is impossible to help
> 
> OS - Windows 7 for NVIDIA rig - 12gb ram / 40gb virtual memory 2x 3080 and 2x 3060 all LHR 3080 set to lock core 1250, and 3060 lock core 1450 Memory overclocks set at +1250 driver 472.12 overclocks set using nvidia smi
> 
> OS - windows 10 for amd rig - 8gb ram / 40gb virtual memory 5x 6600 non XT core set 1750 memory at 1900 overclocks set using msi afterburner 18/10/2021 driver

Could you try meanwhile to run them with MMPOS or HiveOS? To confirm they work properly with a mining OS?

**Comment by nCr78** [comment]
I have a few rigs on a few locations (at least 200 miles apart from each other) and I tried the miner on a different timeframe for each rig as I was still testing it out on each one. Some rigs don't have LHR cards at all, some have mixed etc. All are on windows 10 and most run on 472.12 driver but the point is they all stopped at exactly the same minute so I don't believe it has to do with OS/drivers/OC/LHR etc. I believe it might be network related since even with restarts it wouldn't work on any rig. Suddenly when it worked on one, it worked on all. Hope that gives you some clues.

PS: @Lolliedieb if you're looking for a web-ui api implementation for the miner (t-rex style), I can help 😋

**Comment by Xefier** [comment]
On Windows it mines ETH but gets 0 MH/s on TON. But on Hive OS I may have this issue except it just immediately exits before printing any info out.

**Comment by NudeNULL** [comment]
@Lolliedieb , hello you I wrote that even mining just Ton with exactly the same settings on 1.43 is not working at all and on 1.42 is working without any problems, so it is definitely a problem with the new version of miner

**Comment by jgonzis** [comment]
> I have a few rigs on a few locations (at least 200 miles apart from each other) and I tried the miner on a different timeframe for each rig as I was still testing it out on each one. Some rigs don't have LHR cards at all, some have mixed etc. All are on windows 10 and most run on 472.12 driver but the point is they all stopped at exactly the same minute so I don't believe it has to do with OS/drivers/OC/LHR etc. I believe it might be network related since even with restarts it wouldn't work on any rig. Suddenly when it worked on one, it worked on all. Hope that gives you some clues.
> 
> PS: @Lolliedieb if you're looking for a web-ui api implementation for the miner (t-rex style), I can help 😋

Could you add --log=on --logfile=eth.log  to see if we have some extrainformation of what happens

**Comment by ajgum93** [comment]
i have used this in parameters(don't select DUAL TON in GUI) and it works fine

--dualmode TONDUAL --dualpool https://pool.services.tonwhales.com --dualuser <TON WALLET>

-----

OC Settings: (3x Rtx 3080 nonLHR & 2 Rtx 3080 LHR)


coreclock: 1260
Memclock: 2200
PL: 280


(reboot system after applying this config)

**Comment by Vinasis01** [comment]
> For LHR try using Nvidia Drivers 472.12 please...

I am using that version on my LHR rig, today I tested the mining and it worked for one hour then the same issue started happening again.

Any clarification on what is causing this? as leaving multiple rigs suddenly go down is a loss and is it better to wait for some time till this get resolved?

**Comment by llacee** [comment]
Hi
for me too, this error stops the miner and waits for a keystroke.
rebooting doesn't help either, but it only occurs on windows machines and all of them at once
works well under hiveos.

**Comment by Manolo74410** [comment]
Hello, me too on Windows 10 & 11.

Error "Press any key" after 5s...
Work very good in my HiveOS rig

**Comment by Dizmus** [comment]
Same here. 
3080 TI MSI Suprim X. 

On first launch it was tuning for some time (10-15 minutes) and then this happened. 

Event viewer gives the following Error: 

Faulting application name: lolMiner.exe, version: 0.0.0.0, time stamp: 0x61fcfcd9
Faulting module name: lolMiner.exe, version: 0.0.0.0, time stamp: 0x61fcfcd9
Exception code: 0xc0000005
Fault offset: 0x000000000035b120
Faulting process id: 0x33c0
Faulting application start time: 0x01d81a7df41a1508
Faulting application path: F:\Installs\Mining\lolMiner\lolMiner.exe
Faulting module path: F:\Installs\Mining\lolMiner\lolMiner.exe
Report Id: 68702411-dde2-48c2-9c59-52e341fdfb3f
Faulting package full name: 
Faulting package-relative application ID: 


And the following information:

Fault bucket 2300230519338028940, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: lolMiner.exe
P2: 0.0.0.0
P3: 61fcfcd9
P4: lolMiner.exe
P5: 0.0.0.0
P6: 61fcfcd9
P7: c0000005
P8: 000000000035c880
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.07911f4a-5c2f-4ac0-abd6-59335fee9ac3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.41aca98b-d057-4070-ad72-2d2fd4f9769d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.79b5708c-0c8a-4dbb-a215-8f3da8562c2b.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6aa342cc-49ae-4338-83af-23fd04f443e4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.26313aba-6b72-45c2-a559-7c40bf9b554a.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_lolMiner.exe_16662062b1942dced2589f2c43ecd3db29d8a775_58871e35_05111f0e-5e7d-4a1a-a137-919eeb972832

Analysis symbol: 
Rechecking for solution: 0
Report Id: cedd777a-7d7f-4998-ae0e-f20adca4475e
Report Status: 268435456
Hashed bucket: afaf84f468d006767fec0f785ea7cf8c
Cab Guid: 0



--------------

I was not able to access any of those crash files. Some of them were missing, the report archive is not accessible due to permission. Even replacing owner and giving myself a Full Control doesn't help

**Comment by papnikol** [comment]
Same here

- windows 10 20H2
- AMD 3950X
- 16 GB
- Asus TUF RTX3080
- mining TON on whale pool

works for some time then I get the "press any key..."
reverted to v1.42, no problem

**Comment by nCr78** [comment]
@jgonzis It happened again today at the exact time on all rigs, it's right after "DNS over HTTPS resolve succeeded" every time. Maybe there's still a bug left there since v1.41?

**Comment by jgonzis** [comment]
> @jgonzis It happened again today at the exact time on all rigs, it's right after "DNS over HTTPS resolve succeeded" every time. Maybe there's still a bug left there since v1.41?

Which pool are you using?? 

We found tonwhales.com is having lot of problems of bans, we recommend using ton-pool or better the toncoinpool.io connection

**Comment by papnikol** [comment]
@jgonzis 
I am also using tonwahales and there is no problem with the previous version.

I will try toncoinpool.io  in order to test it (Am I correct that the only thing I have to change in mineton.bat is the pool to `wss://pplns.toncoinpool.io/stratum` ?)

**Comment by nCr78** [comment]
It happened again and indeed it was the connection with ton-whales pool. I tried the "DNS over HTTPS" thing to be off from the settings/arguments but now it crashed right after "Ton pool connection mode: https job polling (ton-miner compatible) (--ton-mode 1)" which was usually right after or before the "DNS over HTTPS" message.

I will try toncoinpool.io and share results.

**Comment by Vinasis01** [comment]
Happened again and the mining stopped

**Comment by Vinasis01** [comment]
> @jgonzis I am also using tonwahales and there is no problem with the previous version.
> 
> I will try toncoinpool.io in order to test it (Am I correct that the only thing I have to change in mine_ton.bat is the pool to `wss://pplns.toncoinpool.io/stratum` ?)

have you tested? if i want to change the pool I just change the pool address?

**Comment by nCr78** [comment]
> have you tested? if i want to change the pool I just change the pool address?

Yes I tested and it works correctly. You just replace it becomes like this:

`set "TONPOOL=wss://pplns.toncoinpool.io/stratum"`

No errors so far. Only issue is the stale shares 5% on Eth Flexpool but the extra profits from dual mining are worth this setback for now. Hopefully it's fixed in next version 😅

**Comment by nissan1973** [comment]
Was doing okay on several rigs last night and now it's a constant with "press any key to continue..."

**Comment by MoacirEduardo** [comment]
I am having the same issue. In my hive os rig is working fine, but in windows every about 3 hours this problems happens.

**Comment by y-naught** [comment]
I also am having the same issue. I have two windows 10 rigs which were mining to Whales Pool and include a mix of Nvidia and AMD cards, which encountered the same issue at the same time. My Ubuntu rig was mining to the same pool only using Nvidia cards and never encountered any issues. I switched to Ton Pool on my Windows machines a few minutes ago and it seems to be humming along fine again, so far.

**Comment by St3ffGv4** [comment]
I'm also having the same issue. Lol miner 1.43, latest Nvidia drivers, windows 10, 4 3060ti FE, 1 3070 FE

**Comment by Mumpitz23** [comment]
lolminer 1.43, NVidia 511.23, Windows 10 and TonWhales
No matter if I'm using ETH+TON or TON I get the Problem mentioned here. Haven't tested another Pool yet.

**Comment by maxouille** [comment]
Same here on dual mining ! Hope it will be fixed soon. It work for like an hour and then stopped...

**Comment by papnikol** [comment]
> @jgonzis I am also using tonwahales and there is no problem with the previous version.
> 
> I will try toncoinpool.io in order to test it (Am I correct that the only thing I have to change in mine_ton.bat is the pool to `wss://pplns.toncoinpool.io/stratum` ?)

Can confirm from my side:
2 hours non-dual mining at toncoinpool.io with no problem.
I then tried whaleton and had the same problem

**Comment by jgonzis** [comment]
> > @jgonzis I am also using tonwahales and there is no problem with the previous version.
> > I will try toncoinpool.io in order to test it (Am I correct that the only thing I have to change in mine_ton.bat is the pool to `wss://pplns.toncoinpool.io/stratum` ?)
> 
> Can confirm from my side: 2 hours non-dual mining at toncoinpool.io with no problem. I then tried tonwahales and had the same problem

tonwhales... it is not working properly... Also remember to select only 1 pool in HiveOS

Also new ICEMining pool... it has a really good protocol.... 

https://icemining.ca/site/coins/id/2431

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/15786742/152606181-66221dcb-9c5c-4ebc-a08f-245bda901a14.png)

That is also a bat file to do autoloop....

@echo off
setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL="
set "WALLET="

set "TONPOOL="
set "TONWALLET="
							
set "EXTRAPARAMETERS="

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10

goto END

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --dualmode TONDUAL --dualpool !TONPOOL! --dualuser !TONWALLET! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW


:END
pause

**Comment by maxouille** [comment]
> > > @jgonzis I am also using tonwahales and there is no problem with the previous version.
> > > I will try toncoinpool.io in order to test it (Am I correct that the only thing I have to change in mine_ton.bat is the pool to `wss://pplns.toncoinpool.io/stratum` ?)
> > 
> > 
> > Can confirm from my side: 2 hours non-dual mining at toncoinpool.io with no problem. I then tried tonwahales and had the same problem
> 
> tonwhales... it is not working properly... Also remember to select only 1 pool in HiveOS
> 
> Also new ICEMining pool... it has a really good protocol....
> 
> https://icemining.ca/site/coins/id/2431

I tried with TON Pool and it seems to work properly. I think the issue is with TonWhales.

**Comment by NudeNULL** [comment]
@maxouille, tonwhales works on 1.42, so the problem cannot be simply because of the pool, they definitely changed something in the miner itself regarding the TONCOIN

**Comment by maxouille** [comment]
> @maxouille, tonwhales works on 1.42, so the problem cannot be simply because of the pool, they definitely changed something in the miner itself regarding the TONCOIN

Yes you are right. At least, there is a fix until the problem is fixed :)

**Comment by jgonzis** [comment]
Servers:
toncoinpool.io: wss://pplns.toncoinpool.io/stratum
ton-pool.com: https://next.ton-pool.com
icemining.ca  ton.hashrate.to:4003

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/15786742/152606181-66221dcb-9c5c-4ebc-a08f-245bda901a14.png)

Confirmed with other pools work... it seems tonwhales pool is not working properly...

use Servers:
toncoinpool.io: wss://pplns.toncoinpool.io/stratum
ton-pool.com: https://next.ton-pool.com
icemining.ca  ton.hashrate.to:4003

**Comment by papnikol** [comment]
> > ![image](https://user-images.githubusercontent.com/15786742/152606181-66221dcb-9c5c-4ebc-a08f-245bda901a14.png)
> 
> Confirmed with other pools work... it seems tonwhales pool is not working properly...
> 
> use Servers: toncoinpool.io: wss://pplns.toncoinpool.io/stratum ton-pool.com: https://next.ton-pool.com icemining.ca ton.hashrate.to:4003

still, as many mentioned, whale works fine with 1.42, which means something changed in 1.43
PS: icemining.ca seems to have a complicated withdrawal method

**Comment by jgonzis** [comment]
> > > ![image](https://user-images.githubusercontent.com/15786742/152606181-66221dcb-9c5c-4ebc-a08f-245bda901a14.png)
> > 
> > 
> > Confirmed with other pools work... it seems tonwhales pool is not working properly...
> > use Servers: toncoinpool.io: wss://pplns.toncoinpool.io/stratum ton-pool.com: https://next.ton-pool.com icemining.ca ton.hashrate.to:4003
> 
> still, as many mentioned, whale works fine with 1.42, which means something changed in 1.43 PS: icemining.ca seems to have a complicated withdrawal method

Also devs confirmed... if you don't believe me see pin in telegram. Meanwhile the ban use other pools

**Comment by papnikol** [comment]
> 
> Also devs confirmed... if you don't believe me see pin in telegram. Meanwhile the ban use other pools

Thanks for the info. Btw, i assure you i never implied i did not believe you, i was just mentioning it because it seemed strange

**Comment by mrmeowserer** [comment]
I am having the same issue. Tonwhalespool and 1.42 works fine, but 1.43 does not and shows same message "press any key to continue."

**Comment by Bleach222** [comment]
I think it has something to do with a signature being revoked

**Comment by nCr78** [comment]
It happened again on one of my rigs mining on toncoinpool.io. This time there was nothing particular printed on command line. No errors, no device issues on event viewer, not even a crash.. It just stopped. At least this time it didn't happen on the rest of the rigs.

**Comment by Rdgordon81** [comment]
> use

Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.

**Comment by jgonzis** [comment]
> > use
> 
> Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.

Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.

So it seems in Windows, we found that tonwhales.com is not working properly. For more help  we really need photos or log and also configuration. 
After  some

**Comment by HardwareSpielerei** [comment]
The crashes occur on Windows 10 Pro 21H1 (build 19043.1466) and on Windows Server 2019 Essentials 1809 (build 17763.2452) for me, but not constantly. That's why I surrounded the batch file with a goto loop:
```
@echo off

:again

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

[...]

:END
timeout 60
goto again
```
From time to time lolMiner 1.43 works using server1.whalestonpool.com for several minutes instead of crashing immediatly. And both instances on both systems seam to crash simultaneously after a "logging period", suggesting an external cause.

Adding...
`set "EXTRAPARAMETERS=--log=on --logfile=ton.log"`
...seems to have no effect. How do I have to use the logging option, please?

**Comment by jgonzis** [comment]
> The crashes occur on Windows 10 Pro 21H1 (build 19043.1466) and on Windows Server 2019 Essentials 1809 (build 17763.2452) for me, but not constantly. That's why I surrounded the batch file with a goto loop:
> 
> ```
> @echo off
> 
> :again
> 
> setlocal enableDelayedExpansion
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> [...]
> 
> :END
> timeout 60
> goto again
> ```
> 
> From time to time lolMiner 1.43 works using server1.whalestonpool.com for several minutes instead of crashing immediatly. And both instances on both systems seam to crash simultaneously after a "mining period", suggesting an external cause.
> 
> Adding... `set "EXTRAPARAMETERS=--log=on --logfile=ton.log"` ...seems to have no effect. How do I have to use the logging option, please?

In release part it is the updated bat file of for mine ETH and TON that solve that bug

**Comment by HardwareSpielerei** [comment]
> > Adding... `set "EXTRAPARAMETERS=--log=on --logfile=ton.log"` ...seems to have no effect. How do I have to use the logging option, please?
> 
> In release part it is the updated bat file of for mine ETH and TON that solve that bug

That works, thank you!

The contents of the log file correspond to the output on the console. Is there an option to increase the log level to provide you with more detailed information?

**Comment by F41nT** [comment]
> > The crashes occur on Windows 10 Pro 21H1 (build 19043.1466) and on Windows Server 2019 Essentials 1809 (build 17763.2452) for me, but not constantly. That's why I surrounded the batch file with a goto loop:
> > ```
> > @echo off
> > 
> > :again
> > 
> > setlocal enableDelayedExpansion
> > 
> > Rem #################################
> > Rem ## Begin of user-editable part ##
> > Rem #################################
> > 
> > [...]
> > 
> > :END
> > timeout 60
> > goto again
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From time to time lolMiner 1.43 works using server1.whalestonpool.com for several minutes instead of crashing immediatly. And both instances on both systems seam to crash simultaneously after a "mining period", suggesting an external cause.
> > Adding... `set "EXTRAPARAMETERS=--log=on --logfile=ton.log"` ...seems to have no effect. How do I have to use the logging option, please?
> 
> In release part it is the updated bat file of for mine ETH and TON that solve that bug

Well I have some sort of bug when connecting to https://pool.services.tonwhales.com/ on HiveOS. After about 30 minutes of mining the miner is restarting. The problem doesn't occur on https://next.ton-pool.com/ - have been mining the whole night without any problems. Cant confirm that It is the same issue (press any key to continue) cause I didnt catch that moment via hive shell but it happens without any messages on hive. I am also running the second miner at the same time and it doesnt reset at all - it just keeps going despite lolminer restart.

Second problem is when I try to connect to wss://pplns.toncoinpool.io/stratum. It gives me the message: received a defect stratum message conversion of data to type b failed. Is it the problem with my network connection?

**Comment by jgonzis** [comment]
> > > The crashes occur on Windows 10 Pro 21H1 (build 19043.1466) and on Windows Server 2019 Essentials 1809 (build 17763.2452) for me, but not constantly. That's why I surrounded the batch file with a goto loop:
> > > ```
> > > @echo off
> > > 
> > > :again
> > > 
> > > setlocal enableDelayedExpansion
> > > 
> > > Rem #################################
> > > Rem ## Begin of user-editable part ##
> > > Rem #################################
> > > 
> > > [...]
> > > 
> > > :END
> > > timeout 60
> > > goto again
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > From time to time lolMiner 1.43 works using server1.whalestonpool.com for several minutes instead of crashing immediatly. And both instances on both systems seam to crash simultaneously after a "mining period", suggesting an external cause.
> > > Adding... `set "EXTRAPARAMETERS=--log=on --logfile=ton.log"` ...seems to have no effect. How do I have to use the logging option, please?
> > 
> > 
> > In release part it is the updated bat file of for mine ETH and TON that solve that bug
> 
> Well I have some sort of bug when connecting to https://pool.services.tonwhales.com/ on HiveOS. After about 30 minutes of mining the miner is restarting. The problem doesn't occur on https://next.ton-pool.com/ - have been mining the whole night without any problems. Cant confirm that It is the same issue (press any key to continue) cause I didnt catch that moment via hive shell but it happens without any messages on hive. I am also running the second miner at the same time and it doesnt reset at all - it just keeps going despite lolminer restart.
> 
> Second problem is when I try to connect to wss://pplns.toncoinpool.io/stratum. It gives me the message: received a defect stratum message conversion of data to type b failed. Is it the problem with my network connection?

It is the same problem.. thx for sharing.

For toncoinpool.io try to write the workername manually. Don't use the %WORKER_NAME%, HiveOS gives a name that doesn't work in rig names with spaces

**Comment by Bleach222** [comment]
> > > use
> > 
> > 
> > Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.
> 
> Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.
> 
> So it seems in Windows, we found that tonwhales.com is not working properly. For more help we really need photos or log and also configuration. After some

3090 and 3070 2 different rigs no settings changed in miner just added wallet address and pool address worked fine for around 12 hours then both went down at the exact time whale is rejecting for some reason its right when it goes to check hash rates it pops up its tripping antivirus i assume because the certificate is revoked by the person who signed it

**Comment by jgonzis** [comment]
> > > > use
> > > 
> > > 
> > > Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.
> > 
> > 
> > Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.
> > So it seems in Windows, we found that tonwhales.com is not working properly. For more help we really need photos or log and also configuration. After some
> 
> 3090 and 3070 2 different rigs no settings changed in miner just added wallet address and pool address worked fine for around 12 hours then both went down at the exact time whale is rejecting for some reason its right when it goes to check hash rates it pops up its tripping antivirus i assume because the certificate is revoked by the person who signed it

Redownload the zip file, but no one change anything... also which pool where you?.

**Comment by BobSaccamano** [comment]
![Screenshot 2022-02-07 04 17 49](https://user-images.githubusercontent.com/83489817/152719540-49d3a0c5-745d-4892-a827-81aa7147f4a6.png)

Left: lolminer 1.43
Right: lolminer 1.42
running identical commands:  .\lolminer.exe -a TON -p https://server1.whalestonpool.com -u EQxxxxxxxxxxxxxxxxxxxxxxxxxx --apiport 4444 --tls 0 --watchdogscript reboot.sh --devices 0,1,2,3,4,6,7

**Comment by Bleach222** [comment]
This is 100% due to lolminer exe being blocked by windows app antivirus and browsers blocking it even after making exceptions for it im still getting all kinds of blocked blocked blocked even after removing and taking control over and deleting antivirus

**Comment by jgonzis** [comment]
> ![Screenshot 2022-02-07 04 17 49](https://user-images.githubusercontent.com/83489817/152719540-49d3a0c5-745d-4892-a827-81aa7147f4a6.png)
> 
> Left: lolminer 1.43 Right: lolminer 1.42 running identical commands: .\lolminer.exe -a TON -p https://server1.whalestonpool.com -u EQxxxxxxxxxxxxxxxxxxxxxxxxxx --apiport 4444 --tls 0 --watchdogscript reboot.sh --devices 0,1,2,3,4,6,7

Totally right, windows 1.43 is not working with tonwhales.com at the moment.  If you try any other pool it will work...

**Comment by jgonzis** [comment]
> This is 100% due to lolminer exe being blocked by windows app antivirus and browsers blocking it even after making exceptions for it im still getting all kinds of blocked blocked blocked even after removing and taking control over and deleting antivirus

Try to excluded and recover it from quarantine

**Comment by Rdgordon81** [comment]
> > > use
> > 
> > 
> > Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.
> 
> Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.
> 
> So it seems in Windows, we found that tonwhales.com is not working properly. For more help we really need photos or log and also configuration. After some

Been testing different things out. And it seems like the problem is much more common, the lower the priority is set for ton. Im only running one rx5700, because of stability issues, but It seems stable when it is set over 1.0, I moved it down to .70 and it will only run for 5 minutes or so before the ton server starts refusing handshake. Once it refuses one handshake, it will sometimes reconnect and see new jobs, sometimes hang immediately, but will always hang within a minute or two with "press key to continue". Since it doesn't crash, watchdog does not get activated. 

Windows 10, next.ton.pool, only extra parameter is --maxdualimpact XX.

**Comment by jgonzis** [comment]
> > > > use
> > > 
> > > 
> > > Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.
> > 
> > 
> > Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.
> > So it seems in Windows, we found that tonwhales.com is not working properly. For more help we really need photos or log and also configuration. After some
> 
> Been testing different things out. And it seems like the problem is much more common, the lower the priority is set for ton. Im only running one rx5700, because of stability issues, but It seems stable when it is set over 1.0, I moved it down to .70 and it will only run for 5 minutes or so before the ton server starts refusing handshake. Once it refuses one handshake, it will sometimes reconnect and see new jobs, sometimes hang immediately, but will always hang within a minute or two with "press key to continue". Since it doesn't crash, watchdog does not get activated.
> 
> Windows 10, next.ton.pool, only extra parameter is --maxdualimpact XX.

Have you undervolt the 5700?. Try to have it without undervolt, eth+ton needs more voltage than only eth

**Comment by Michael77Vienna** [comment]
> 
next.ton.pool is only running with TON-Pool Miner, am i right?! 
Can i also dual mine with this miner?

**Comment by Michael77Vienna** [comment]
> > > > use
> > > 
> > > 
> > > Same problem is happening on next.ton pool. So whatever it is, isn't pool specific.
> > 
> > 
> > Please, to help we need information without information, it is impossible to help. We know with MMPOS.EU or HiveOS is working all perfectly for all users.
> > So it seems in Windows, we found that tonwhales.com is not working properly. For more help we really need photos or log and also configuration. After some
> 
> Been testing different things out. And it seems like the problem is much more common, the lower the priority is set for ton. Im only running one rx5700, because of stability issues, but It seems stable when it is set over 1.0, I moved it down to .70 and it will only run for 5 minutes or so before the ton server starts refusing handshake. Once it refuses one handshake, it will sometimes reconnect and see new jobs, sometimes hang immediately, but will always hang within a minute or two with "press key to continue". Since it doesn't crash, watchdog does not get activated.
> 
> Windows 10, next.ton.pool, only extra parameter is --maxdualimpact XX.

next.ton.pool is only running with TON-Pool Miner, am i right?!
Can i also dual mine with this miner?

**Comment by mrmeowserer** [comment]
Version 1.44 is out I'm going to see if issue is fixed.


________________________________

**Comment by mrmeowserer** [comment]
With version 1.44 dual mining eth and ton is working well so far!

**Comment by jgonzis** [comment]
1.44 Should solve the tonwhales pool problem

**Comment by ZombieWorm** [comment]
This still happens for me. Usually when I am asleep so act on it belatedly. Running version 1.46 and on the ton-pool.

Rig doesnt crash. The batch file just has a blip and has the press any key message. Restart the miner and its grand again for hours/days until it occurs again.

Could be comms between miner and pool as I also get credited by pool 'compensation' so maybe the TON pool goes down not helping.

**Comment by jgonzis** [comment]
> This still happens for me. Usually when I am asleep so act on it belatedly. Running version 1.46 and on the ton-pool.
> 
> Rig doesnt crash. The batch file just has a blip and has the press any key message. Restart the miner and its grand again for hours/days until it occurs again.
> 
> Could be comms between miner and pool as I also get credited by pool 'compensation' so maybe the TON pool goes down not helping.

In the wiki Section there is  Guide for Windows with a bat file that has a watchdog that could help you to avoid and auto restart in case of crash
