### ISSUE TITLE
watchdog script throws error on windows

### ISSUE THREAD

**Issue by jeff-k-lee** [Lolliedieb/lolMiner-releases#24]
Looks like lolMiner.exe watchdog script throws the following error when miners idle:
> '.' is not recognized as an internal or external command, operable program or batch file.

Windows doesn't seem to accept forward slashes in cmd.exe. This error appears to be replicated in cmd.exe
```
d:\lolMiner 0.9.2>./reboot.bat
'.' is not recognized as an internal or external command,
operable program or batch file.

d:\lolMiner 0.9.2>.\reboot.bat
d:\lolMiner 0.9.2>setlocal enableDelayedExpansion
d:\lolMiner 0.9.2>Rem ##################################
d:\lolMiner 0.9.2>Rem ## Emergency script in case the ##
d:\lolMiner 0.9.2>Rem ## miner crashes. User defined  ##
d:\lolMiner 0.9.2>Rem ## actions to be inserted here  ##
d:\lolMiner 0.9.2>Rem ##################################
etc ...
```

Strangely it does not seem to be an issue with powershell

**Comment by Lolliedieb** [comment]
This should be fixed with 0.9.3 or newer - can you check?

**Comment by jeff-k-lee** [comment]
Sorry, just tested it locally (by resetting the device driver) and it appears the watchdog script works perfectly on windows now!

Thumbs up!

**Comment by lgordo35** [comment]
I am still getting the above code. can someone help me walk through this?
lukeagordon@gmail.com
