### ISSUE TITLE
Broken mining

### ISSUE THREAD

**Issue by KryptoZi** [Lolliedieb/lolMiner-releases#49]
Was trying out your miner today and found that mining Aion is broken, the miner gets job from the pool (tested multiple pools) then crash once it solve a share. I saw in the past some users was reporting that Aion got broken since version 0.7

Example miner command:
lolMiner.exe --coin AION --pool cluster.aionpool.tech:3333 --user walletAddress.workerName --pass mp=10

Example miner command (TLS/SSL):
lolMiner.exe --coin AION --pool cluster.aionpool.tech:5555 --tls on --user walletAddress.workerName --pass mp=10

Screenshot:
![Capture](https://user-images.githubusercontent.com/27823268/86177503-0e85f480-bb27-11ea-8754-59a0c1b61e02.PNG)

**Comment by Lolliedieb** [comment]
Could be an issue with the Nvidia solver ... at least on AMDs I receive valid shares. Interesting. I will have a look if there is an easy fix.

**Comment by Lolliedieb** [comment]
There was a bug in 1.02 and older that the miner did crash right after start  when the API was used. Should be fixed with 1.03.
May you test if its solved?

**Comment by KryptoZi** [comment]
Hello @Lolliedieb, Thank you for following up.
Still having the same problem, could it be something on my end?
I'm testing with a GTX 1080Ti with latest Nvidia drivers "Version: 451.48"
Other coins like Beam is hashing as it should.
![Capture](https://user-images.githubusercontent.com/27823268/86537488-b583db00-beef-11ea-8baf-de784b33eac6.PNG)

**Comment by Lolliedieb** [comment]
Should be fixed with 1.05
